
server:
  port: 8088
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:

mybatis:
  config-locations: classpath:mybatis-config.xml  # mybatis-config.xml文件存放路径
  mapper-locations: classpath:mapper/*.xml  # mapper.xml文件存放路径
  type-aliases-package: com.houxin.electron.demo.mapper.dao  # 实体类存放路径
