package com.houxin.electron.demo.mapper.model;

import java.util.Date;

public class Station {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_station.station_id
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    private Integer stationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_station.station_code
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    private String stationCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_station.station_name
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    private String stationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_station.station_province
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    private String stationProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_station.station_city_code
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    private String stationCityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_station.station_pinyin
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    private String stationPinyin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_station.station_fpinyin
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    private String stationFpinyin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_station.create_time
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_station.station_desc
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    private String stationDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_station.station_id
     *
     * @return the value of s_station.station_id
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public Integer getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_station.station_id
     *
     * @param stationId the value for s_station.station_id
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public void setStationId(Integer stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_station.station_code
     *
     * @return the value of s_station.station_code
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public String getStationCode() {
        return stationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_station.station_code
     *
     * @param stationCode the value for s_station.station_code
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public void setStationCode(String stationCode) {
        this.stationCode = stationCode == null ? null : stationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_station.station_name
     *
     * @return the value of s_station.station_name
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public String getStationName() {
        return stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_station.station_name
     *
     * @param stationName the value for s_station.station_name
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public void setStationName(String stationName) {
        this.stationName = stationName == null ? null : stationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_station.station_province
     *
     * @return the value of s_station.station_province
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public String getStationProvince() {
        return stationProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_station.station_province
     *
     * @param stationProvince the value for s_station.station_province
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public void setStationProvince(String stationProvince) {
        this.stationProvince = stationProvince == null ? null : stationProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_station.station_city_code
     *
     * @return the value of s_station.station_city_code
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public String getStationCityCode() {
        return stationCityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_station.station_city_code
     *
     * @param stationCityCode the value for s_station.station_city_code
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public void setStationCityCode(String stationCityCode) {
        this.stationCityCode = stationCityCode == null ? null : stationCityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_station.station_pinyin
     *
     * @return the value of s_station.station_pinyin
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public String getStationPinyin() {
        return stationPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_station.station_pinyin
     *
     * @param stationPinyin the value for s_station.station_pinyin
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public void setStationPinyin(String stationPinyin) {
        this.stationPinyin = stationPinyin == null ? null : stationPinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_station.station_fpinyin
     *
     * @return the value of s_station.station_fpinyin
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public String getStationFpinyin() {
        return stationFpinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_station.station_fpinyin
     *
     * @param stationFpinyin the value for s_station.station_fpinyin
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public void setStationFpinyin(String stationFpinyin) {
        this.stationFpinyin = stationFpinyin == null ? null : stationFpinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_station.create_time
     *
     * @return the value of s_station.create_time
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_station.create_time
     *
     * @param createTime the value for s_station.create_time
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_station.station_desc
     *
     * @return the value of s_station.station_desc
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public String getStationDesc() {
        return stationDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_station.station_desc
     *
     * @param stationDesc the value for s_station.station_desc
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public void setStationDesc(String stationDesc) {
        this.stationDesc = stationDesc == null ? null : stationDesc.trim();
    }
}