package com.houxin.electron.demo.mapper.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_station
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_station
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_station
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_station
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public StationExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_station
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_station
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_station
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_station
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_station
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_station
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_station
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_station
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_station
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_station
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s_station
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStationIdIsNull() {
            addCriterion("station_id is null");
            return (Criteria) this;
        }

        public Criteria andStationIdIsNotNull() {
            addCriterion("station_id is not null");
            return (Criteria) this;
        }

        public Criteria andStationIdEqualTo(Integer value) {
            addCriterion("station_id =", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotEqualTo(Integer value) {
            addCriterion("station_id <>", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdGreaterThan(Integer value) {
            addCriterion("station_id >", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("station_id >=", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdLessThan(Integer value) {
            addCriterion("station_id <", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdLessThanOrEqualTo(Integer value) {
            addCriterion("station_id <=", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdIn(List<Integer> values) {
            addCriterion("station_id in", values, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotIn(List<Integer> values) {
            addCriterion("station_id not in", values, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdBetween(Integer value1, Integer value2) {
            addCriterion("station_id between", value1, value2, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotBetween(Integer value1, Integer value2) {
            addCriterion("station_id not between", value1, value2, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationCodeIsNull() {
            addCriterion("station_code is null");
            return (Criteria) this;
        }

        public Criteria andStationCodeIsNotNull() {
            addCriterion("station_code is not null");
            return (Criteria) this;
        }

        public Criteria andStationCodeEqualTo(String value) {
            addCriterion("station_code =", value, "stationCode");
            return (Criteria) this;
        }

        public Criteria andStationCodeNotEqualTo(String value) {
            addCriterion("station_code <>", value, "stationCode");
            return (Criteria) this;
        }

        public Criteria andStationCodeGreaterThan(String value) {
            addCriterion("station_code >", value, "stationCode");
            return (Criteria) this;
        }

        public Criteria andStationCodeGreaterThanOrEqualTo(String value) {
            addCriterion("station_code >=", value, "stationCode");
            return (Criteria) this;
        }

        public Criteria andStationCodeLessThan(String value) {
            addCriterion("station_code <", value, "stationCode");
            return (Criteria) this;
        }

        public Criteria andStationCodeLessThanOrEqualTo(String value) {
            addCriterion("station_code <=", value, "stationCode");
            return (Criteria) this;
        }

        public Criteria andStationCodeLike(String value) {
            addCriterion("station_code like", value, "stationCode");
            return (Criteria) this;
        }

        public Criteria andStationCodeNotLike(String value) {
            addCriterion("station_code not like", value, "stationCode");
            return (Criteria) this;
        }

        public Criteria andStationCodeIn(List<String> values) {
            addCriterion("station_code in", values, "stationCode");
            return (Criteria) this;
        }

        public Criteria andStationCodeNotIn(List<String> values) {
            addCriterion("station_code not in", values, "stationCode");
            return (Criteria) this;
        }

        public Criteria andStationCodeBetween(String value1, String value2) {
            addCriterion("station_code between", value1, value2, "stationCode");
            return (Criteria) this;
        }

        public Criteria andStationCodeNotBetween(String value1, String value2) {
            addCriterion("station_code not between", value1, value2, "stationCode");
            return (Criteria) this;
        }

        public Criteria andStationNameIsNull() {
            addCriterion("station_name is null");
            return (Criteria) this;
        }

        public Criteria andStationNameIsNotNull() {
            addCriterion("station_name is not null");
            return (Criteria) this;
        }

        public Criteria andStationNameEqualTo(String value) {
            addCriterion("station_name =", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameNotEqualTo(String value) {
            addCriterion("station_name <>", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameGreaterThan(String value) {
            addCriterion("station_name >", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameGreaterThanOrEqualTo(String value) {
            addCriterion("station_name >=", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameLessThan(String value) {
            addCriterion("station_name <", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameLessThanOrEqualTo(String value) {
            addCriterion("station_name <=", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameLike(String value) {
            addCriterion("station_name like", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameNotLike(String value) {
            addCriterion("station_name not like", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameIn(List<String> values) {
            addCriterion("station_name in", values, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameNotIn(List<String> values) {
            addCriterion("station_name not in", values, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameBetween(String value1, String value2) {
            addCriterion("station_name between", value1, value2, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameNotBetween(String value1, String value2) {
            addCriterion("station_name not between", value1, value2, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationProvinceIsNull() {
            addCriterion("station_province is null");
            return (Criteria) this;
        }

        public Criteria andStationProvinceIsNotNull() {
            addCriterion("station_province is not null");
            return (Criteria) this;
        }

        public Criteria andStationProvinceEqualTo(String value) {
            addCriterion("station_province =", value, "stationProvince");
            return (Criteria) this;
        }

        public Criteria andStationProvinceNotEqualTo(String value) {
            addCriterion("station_province <>", value, "stationProvince");
            return (Criteria) this;
        }

        public Criteria andStationProvinceGreaterThan(String value) {
            addCriterion("station_province >", value, "stationProvince");
            return (Criteria) this;
        }

        public Criteria andStationProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("station_province >=", value, "stationProvince");
            return (Criteria) this;
        }

        public Criteria andStationProvinceLessThan(String value) {
            addCriterion("station_province <", value, "stationProvince");
            return (Criteria) this;
        }

        public Criteria andStationProvinceLessThanOrEqualTo(String value) {
            addCriterion("station_province <=", value, "stationProvince");
            return (Criteria) this;
        }

        public Criteria andStationProvinceLike(String value) {
            addCriterion("station_province like", value, "stationProvince");
            return (Criteria) this;
        }

        public Criteria andStationProvinceNotLike(String value) {
            addCriterion("station_province not like", value, "stationProvince");
            return (Criteria) this;
        }

        public Criteria andStationProvinceIn(List<String> values) {
            addCriterion("station_province in", values, "stationProvince");
            return (Criteria) this;
        }

        public Criteria andStationProvinceNotIn(List<String> values) {
            addCriterion("station_province not in", values, "stationProvince");
            return (Criteria) this;
        }

        public Criteria andStationProvinceBetween(String value1, String value2) {
            addCriterion("station_province between", value1, value2, "stationProvince");
            return (Criteria) this;
        }

        public Criteria andStationProvinceNotBetween(String value1, String value2) {
            addCriterion("station_province not between", value1, value2, "stationProvince");
            return (Criteria) this;
        }

        public Criteria andStationCityCodeIsNull() {
            addCriterion("station_city_code is null");
            return (Criteria) this;
        }

        public Criteria andStationCityCodeIsNotNull() {
            addCriterion("station_city_code is not null");
            return (Criteria) this;
        }

        public Criteria andStationCityCodeEqualTo(String value) {
            addCriterion("station_city_code =", value, "stationCityCode");
            return (Criteria) this;
        }

        public Criteria andStationCityCodeNotEqualTo(String value) {
            addCriterion("station_city_code <>", value, "stationCityCode");
            return (Criteria) this;
        }

        public Criteria andStationCityCodeGreaterThan(String value) {
            addCriterion("station_city_code >", value, "stationCityCode");
            return (Criteria) this;
        }

        public Criteria andStationCityCodeGreaterThanOrEqualTo(String value) {
            addCriterion("station_city_code >=", value, "stationCityCode");
            return (Criteria) this;
        }

        public Criteria andStationCityCodeLessThan(String value) {
            addCriterion("station_city_code <", value, "stationCityCode");
            return (Criteria) this;
        }

        public Criteria andStationCityCodeLessThanOrEqualTo(String value) {
            addCriterion("station_city_code <=", value, "stationCityCode");
            return (Criteria) this;
        }

        public Criteria andStationCityCodeLike(String value) {
            addCriterion("station_city_code like", value, "stationCityCode");
            return (Criteria) this;
        }

        public Criteria andStationCityCodeNotLike(String value) {
            addCriterion("station_city_code not like", value, "stationCityCode");
            return (Criteria) this;
        }

        public Criteria andStationCityCodeIn(List<String> values) {
            addCriterion("station_city_code in", values, "stationCityCode");
            return (Criteria) this;
        }

        public Criteria andStationCityCodeNotIn(List<String> values) {
            addCriterion("station_city_code not in", values, "stationCityCode");
            return (Criteria) this;
        }

        public Criteria andStationCityCodeBetween(String value1, String value2) {
            addCriterion("station_city_code between", value1, value2, "stationCityCode");
            return (Criteria) this;
        }

        public Criteria andStationCityCodeNotBetween(String value1, String value2) {
            addCriterion("station_city_code not between", value1, value2, "stationCityCode");
            return (Criteria) this;
        }

        public Criteria andStationPinyinIsNull() {
            addCriterion("station_pinyin is null");
            return (Criteria) this;
        }

        public Criteria andStationPinyinIsNotNull() {
            addCriterion("station_pinyin is not null");
            return (Criteria) this;
        }

        public Criteria andStationPinyinEqualTo(String value) {
            addCriterion("station_pinyin =", value, "stationPinyin");
            return (Criteria) this;
        }

        public Criteria andStationPinyinNotEqualTo(String value) {
            addCriterion("station_pinyin <>", value, "stationPinyin");
            return (Criteria) this;
        }

        public Criteria andStationPinyinGreaterThan(String value) {
            addCriterion("station_pinyin >", value, "stationPinyin");
            return (Criteria) this;
        }

        public Criteria andStationPinyinGreaterThanOrEqualTo(String value) {
            addCriterion("station_pinyin >=", value, "stationPinyin");
            return (Criteria) this;
        }

        public Criteria andStationPinyinLessThan(String value) {
            addCriterion("station_pinyin <", value, "stationPinyin");
            return (Criteria) this;
        }

        public Criteria andStationPinyinLessThanOrEqualTo(String value) {
            addCriterion("station_pinyin <=", value, "stationPinyin");
            return (Criteria) this;
        }

        public Criteria andStationPinyinLike(String value) {
            addCriterion("station_pinyin like", value, "stationPinyin");
            return (Criteria) this;
        }

        public Criteria andStationPinyinNotLike(String value) {
            addCriterion("station_pinyin not like", value, "stationPinyin");
            return (Criteria) this;
        }

        public Criteria andStationPinyinIn(List<String> values) {
            addCriterion("station_pinyin in", values, "stationPinyin");
            return (Criteria) this;
        }

        public Criteria andStationPinyinNotIn(List<String> values) {
            addCriterion("station_pinyin not in", values, "stationPinyin");
            return (Criteria) this;
        }

        public Criteria andStationPinyinBetween(String value1, String value2) {
            addCriterion("station_pinyin between", value1, value2, "stationPinyin");
            return (Criteria) this;
        }

        public Criteria andStationPinyinNotBetween(String value1, String value2) {
            addCriterion("station_pinyin not between", value1, value2, "stationPinyin");
            return (Criteria) this;
        }

        public Criteria andStationFpinyinIsNull() {
            addCriterion("station_fpinyin is null");
            return (Criteria) this;
        }

        public Criteria andStationFpinyinIsNotNull() {
            addCriterion("station_fpinyin is not null");
            return (Criteria) this;
        }

        public Criteria andStationFpinyinEqualTo(String value) {
            addCriterion("station_fpinyin =", value, "stationFpinyin");
            return (Criteria) this;
        }

        public Criteria andStationFpinyinNotEqualTo(String value) {
            addCriterion("station_fpinyin <>", value, "stationFpinyin");
            return (Criteria) this;
        }

        public Criteria andStationFpinyinGreaterThan(String value) {
            addCriterion("station_fpinyin >", value, "stationFpinyin");
            return (Criteria) this;
        }

        public Criteria andStationFpinyinGreaterThanOrEqualTo(String value) {
            addCriterion("station_fpinyin >=", value, "stationFpinyin");
            return (Criteria) this;
        }

        public Criteria andStationFpinyinLessThan(String value) {
            addCriterion("station_fpinyin <", value, "stationFpinyin");
            return (Criteria) this;
        }

        public Criteria andStationFpinyinLessThanOrEqualTo(String value) {
            addCriterion("station_fpinyin <=", value, "stationFpinyin");
            return (Criteria) this;
        }

        public Criteria andStationFpinyinLike(String value) {
            addCriterion("station_fpinyin like", value, "stationFpinyin");
            return (Criteria) this;
        }

        public Criteria andStationFpinyinNotLike(String value) {
            addCriterion("station_fpinyin not like", value, "stationFpinyin");
            return (Criteria) this;
        }

        public Criteria andStationFpinyinIn(List<String> values) {
            addCriterion("station_fpinyin in", values, "stationFpinyin");
            return (Criteria) this;
        }

        public Criteria andStationFpinyinNotIn(List<String> values) {
            addCriterion("station_fpinyin not in", values, "stationFpinyin");
            return (Criteria) this;
        }

        public Criteria andStationFpinyinBetween(String value1, String value2) {
            addCriterion("station_fpinyin between", value1, value2, "stationFpinyin");
            return (Criteria) this;
        }

        public Criteria andStationFpinyinNotBetween(String value1, String value2) {
            addCriterion("station_fpinyin not between", value1, value2, "stationFpinyin");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s_station
     *
     * @mbg.generated do_not_delete_during_merge Sun Nov 10 14:45:44 CST 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s_station
     *
     * @mbg.generated Sun Nov 10 14:45:44 CST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}